spring:
  application:
    name: hello-spring-cloud-config

  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.17.137/wck95/spring-cloud-config.git
          search-paths: respo
          username: wck95
          password: wck951210

  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


